apiVersion: skaffold/v2beta23
kind: Config
metadata:
  name: SongtrackerPro
build:
  tagPolicy:
    sha256: {}

  local:
    concurrency: 4
    useBuildkit: false
    useDockerCLI: true

  artifacts:
    - image: songtracker-pro-api
      context: Server
      docker:
        dockerfile: Dockerfile
        noCache: false
        squash: false
        target: final
    - image: songtracker-pro-web
      context: Web
      docker:
        dockerfile: Dockerfile
        noCache: false
        squash: false
        target: final
deploy:
  statusCheckDeadlineSeconds: 300
  kubeContext: docker-desktop
  kustomize:
    paths:
      - Server/k8s/local
