apiVersion: v1
kind: ServiceAccount
metadata:
  name: dev
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: dev
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: dev
  namespace: kube-system
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: default
  namespace: local
imagePullSecrets:
- name: gcp-json-key
