apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  selector:
    app: postgres
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
    - port: 5432
      targetPort: 5432
