apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  serviceName: postgres
  selector:
    matchLabels:
      app: postgres
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: postgres
    spec:
      hostNetwork: true
      containers:
        - name: postgres
          ports:
            - containerPort: 5432
              hostPort: 5432
          environment:
            - name: POSTGRES_USER
              value: root
            - name: POSTGRES_PASSWORD
              value: root
            - name: POSTGRES_DB
              value: soundtracker-pro
            - name: PGDATA
              value: /data/postgres
          volumeMounts:
            - name: postgres-data
              mountPath: /data
              subPath: postgres
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-pvc
