apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: stable
provisioner: docker.io/hostpath
reclaimPolicy: Retain
volumeBindingMode: Immediate
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: fast
provisioner: docker.io/hostpath
reclaimPolicy: Retain
volumeBindingMode: Immediate