apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: reloader-reloader   
  name: reloader-reloader
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: reloader-reloader
  template:
    metadata:
      labels:
        app: reloader-reloader   
        
    spec:
      containers:
      - image: "stakater/reloader:v0.0.60"
        imagePullPolicy: IfNotPresent
        name: reloader-reloader
        resources:
          limits:
            cpu: 100m
            memory: 320M
          requests:
            cpu: 100m
            memory: 320M
      serviceAccountName: reloader-reloader